import { EmptyNode, RedLaserNode, LCNode } from "@/store/types";

const redLaserNode: RedLaserNode = { type: "red-laser", position: "bottom" };
const emptyNode: EmptyNode = { type: "empty" };

export const initialNodes: LCNode[] = [
  // row 1
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 2
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 3
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 4
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 5
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 6
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 7
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 8
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 9
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  // row 10
  redLaserNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
  emptyNode,
];
