import {
  IEmptyCell,
  IRedLaserCell,
  IYellowLaserCell,
  IRedFireCell,
  IYellowFireCell,
  Cell,
} from "@/store/types";

const redLaserCell: IRedLaserCell = { type: "red-laser", position: "bottom" };
const yellowLaserCell: IYellowLaserCell = {
  type: "yellow-laser",
  position: "up",
};
const emptyCell: IEmptyCell = { type: "empty" };
const redFireCell: IRedFireCell = { type: "red-fire" };
const yellowFireCell: IYellowFireCell = { type: "yellow-fire" };

export const initialCells: Cell[] = [
  // row 1
  redLaserCell,
  yellowFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  redFireCell,
  yellowFireCell,
  // row 2
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 3
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 4
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 5
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 6
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 7
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 8
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 9
  redFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  yellowFireCell,
  // row 10
  redFireCell,
  yellowFireCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  emptyCell,
  redFireCell,
  yellowLaserCell,
];
